name: Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
    version:
      description: 'Version to deploy'
      required: true
      type: string
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, linux, deploy]

    steps:
      - name: Set XDG_RUNTIME_DIR
        run: echo "XDG_RUNTIME_DIR=/run/user/1000" >> $GITHUB_ENV
      - name: download release
        id: download_release
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.whl'
      # - name: copy release file
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ vars.HOST }}
      #     username: ${{ vars.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     source: ${{ fromJson(steps.download_release.outputs.downloaded_files)[0] }}
      #     target: /gritadm/usage_reports/releases/
      - name: copy release file
        uses: garygrossgarten/github-action-scp@0.9.0
        with:
          local: ${{ fromJson(steps.download_release.outputs.downloaded_files)[0] }}
          remote: /gritadm/usage_reports/releases/
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          privateKey: ${{ secrets.KEY }}
      - name: install release
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            FILENAME="$(basename '${{ fromJson(steps.download_release.outputs.downloaded_files)[0] }}')"
            sudo pip install --force-reinstall --break-system-packages ~/usage_reports/releases/github/workspace/$FILENAME
      - uses: actions/checkout@v4

